version: '3.9'

services:
  eventive.api:
    image: ${DOCKER_REGISTRY-}eventiveapi
    container_name: Eventive.Api
    build:
      context: .
      dockerfile: src/API/Eventive.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

  eventive.database:
    image: postgres:latest
    container_name: Eventive.Database
    environment:
      - POSTGRES_DB=eventive
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  eventive.seq:
    image: datalust/seq:latest
    container_name: Eventive.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
